[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200

remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "v4-core/=lib/v4-core/src/",
  "@uniswap/v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/src/",
  "@uniswap/v4-periphery/=lib/v4-periphery/src/",
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/ds-test/src/",
  "solmate/=lib/solmate/src/",
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
